default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: <%= ENV["POSTGRES_DATABASE_PASSWORD"] %>

development:
  <<: *default
  host: localhost
  port: 5433
  database: <%= ENV["PG_TEST"] %>

test: &test
  <<: *default
  host: localhost
  port: 5433
  database: <%= ENV["PG_DEV"] %>

production:
  <<: *default
  host: localhost
  port: 5433
  database: <%= ENV["PG_PROD"] %>
