default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: <%= ENV["POSTGRES_DATABASE_PASSWORD"] %>

development:
  <<: *default
  host: localhost
  port: 5433
  database: brimob_rails_dev

test: &test
  <<: *default
  host: localhost
  port: 5433
  database: brimob_rails_test

production:
  <<: *default
  host: localhost
  port: 5433
  database: brimob_rails
